openapi: 3.0.0
info:
  title: Spotify Tool API
  description: API to facilitate interaction with Spotify
  version: 0.0.1
paths:
  /artists:
    get:
      summary: Gets the data on the artist
      operationId: controller.get_artists
      responses:
        200:
          description: okay response
        404:
          description: not found
